import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const SitePreferencesContext = createContext(null);

const copy = {
  en: {
    controls: {
      themeLight: 'Light mode',
      themeDark: 'Dark mode',
      language: 'Language',
      english: 'EN',
      swahili: 'SW',
    },
    nav: {
      home: 'Home',
      services: 'Services',
      identity: 'Identity',
      insights: 'Insights',
      developers: 'Developers',
      contact: 'Contact',
      more: 'More',
      careers: 'Careers',
      shop: 'Shop',
      support: 'Xempi support',
      solutions: 'Solutions',
      searchPlaceholder: 'Search security services',
      searchServices: 'Search services',
      requestAssessment: 'Request assessment',
    },
    topbar: {
      hours: 'Mon-Fri: 9AM-5PM',
      login: 'Login',
      signup: 'Sign Up',
    },
    auth: {
      loginTitle: 'Login to your SeptaGreen account',
      signupTitle: 'Create a SeptaGreen account',
      email: 'Email address',
      workEmail: 'Work email',
      password: 'Password',
      confirmPassword: 'Confirm password',
      fullName: 'Full name',
      remember: 'Remember me',
      forgot: 'Forgot password?',
      signIn: 'Sign in',
      signingIn: 'Signing in...',
      signUp: 'Sign up',
      processing: 'Processing...',
      loginSuccess: 'Login successful.',
      signupSuccess: 'Account created successfully.',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account? Login',
      emailPlaceholder: 'Enter your email address',
      passwordPlaceholder: 'Enter your password',
      passwordRules: 'Password must contain:',
      ruleLength: 'At least 8 characters',
      ruleUppercase: 'One uppercase letter',
      ruleLowercase: 'One lowercase letter',
      ruleNumber: 'One number',
      ruleSpecial: 'One special character',
    },
    home: {
      badge: 'Offensive security, secure platforms, and managed protection',
      title: "Cybersecurity intelligence for Africa's digital builders.",
      body: 'SeptaGreen helps teams build, test, and monitor digital systems before attackers turn weak points into business disruption.',
      primary: 'Request assessment',
      secondary: 'Explore services',
    },
    mid: {
      kicker: 'Security assurance',
      title: 'Evidence-led security for teams that have to move fast.',
      body: 'Every engagement is designed around decision-ready findings, technical proof, and next steps your engineers and executives can understand.',
      rhythmKicker: 'Operating rhythm',
      rhythmTitle: 'From assessment to action.',
      consultant: 'Talk to a security consultant',
    },
    services: {
      kicker: 'Professional security testing services',
      title: 'Test your defenses before attackers do.',
      body: 'SeptaGreen combines offensive security, secure digital product delivery, cloud review, and managed monitoring for teams that need visible risk reduction.',
      discover: 'Discover our services for',
      discoverTitle: 'Modern teams, critical systems, and digital growth.',
      learnMore: 'Learn more',
    },
    contact: {
      kicker: 'Request assessment',
      title: 'Protect your business against current cyber threats.',
      body: 'Tell us about the systems, cloud workloads, applications, or users you need reviewed. We will scope a practical assessment and follow up with the right next step.',
      phoneTitle: 'Prefer a direct conversation?',
      phoneBody: 'Call the team for urgent scoping or send the form for a structured assessment request.',
      emailLabel: 'Email',
      location: 'Location',
      nextTitle: 'What happens next',
      nextSteps: [
        'We review your systems, goals, and timeline.',
        'We recommend a scoped assessment track.',
        'You receive a clear next step and delivery estimate.',
      ],
      formTitle: 'Get an assessment scope',
      formBody: 'Share enough context for us to recommend the right security path.',
      firstName: 'First name',
      lastName: 'Last name',
      email: 'Corporate email',
      phone: 'Phone',
      company: 'Company name',
      service: 'Service needed',
      offensive: 'Offensive security service',
      penetration: 'Penetration testing service',
      cloud: 'Cloud security service',
      app: 'Application security service',
      managed: 'Managed cybersecurity service',
      solution: 'Solution needed',
      timeline: 'Timeline',
      timelineOptions: ['This month', '1-3 months', 'This quarter', 'Exploratory'],
      message: 'Project context',
      messagePlaceholder: 'Systems, URLs, cloud platforms, compliance needs, or known concerns',
      submit: 'Request assessment',
      success: 'Thanks. The SeptaGreen team will follow up with a scoped next step.',
    },
    identity: {
      missionKicker: 'SeptaGreen identity',
      missionTitle: 'African cybersecurity, designed with discipline.',
      missionBody: 'SeptaGreen exists for organizations that need secure digital growth without theatre. We combine product engineering, offensive testing, and operational clarity so teams know what to fix, why it matters, and how to keep improving.',
      missionCta: 'Request an assessment',
      signals: [
        ['Build securely', 'Product interfaces, APIs, and platforms are treated as security surfaces from day one.'],
        ['Test realistically', 'Assessment work focuses on credible attack paths, not inflated reports.'],
        ['Report clearly', 'Findings are written for the people who have to fund, fix, and verify the work.'],
      ],
      valuesKicker: 'Operating principles',
      valuesTitle: 'What guides the work.',
      valuesBody: 'The brand should feel rigorous, local, and calm under pressure. These principles keep the visual identity and delivery model aligned.',
      values: [
        ['Integrity over theatre', 'We keep findings precise, reproducible, and useful. No inflated risk language where clear evidence is enough.'],
        ['Measured execution', 'Security work has to respect uptime, business context, engineering capacity, and the realities of growing teams.'],
        ['Africa-aware design', 'The operating environment matters: payments, mobile-first users, local infrastructure, and regional compliance pressures.'],
        ['Partnership mindset', 'We work close to the teams responsible for fixes so security becomes a repeatable habit, not a one-off report.'],
      ],
      timelineKicker: 'Company path',
      timelineTitle: 'A grounded roadmap, not borrowed hype.',
      timelineBody: 'The site should communicate momentum without pretending to be larger than it is. This timeline keeps the story credible and current.',
      milestones: [
        ['2025', 'Foundation in Kenya', 'SeptaGreen starts with a combined focus on secure software delivery, penetration testing, and practical cyber advisory for African teams.'],
        ['2026', 'Assessment-first delivery', 'The public service model is sharpened around red team simulation, application security, cloud review, and managed visibility.'],
        ['Next', 'Developer enablement', 'DeveloperX expands the brand into secure builder support: standards, checklists, product reviews, and security-minded engineering practice.'],
        ['Scale', 'Continuous improvement', 'SeptaGreen grows toward recurring monitoring, retesting, reporting, and long-term security partnership for clients.'],
      ],
      leadershipKicker: 'Leadership',
      leadershipTitle: 'Built by practitioners close to the work.',
      leadershipBody: 'The leadership story is intentionally direct: show the person behind the work, the operating philosophy, and the routes to verify credibility.',
      leaderRole: 'Founder and Lead Builder',
      leaderBio: 'William brings together software development, cybersecurity practice, and product thinking. SeptaGreen reflects that overlap: usable digital products, stronger security posture, and practical guidance for teams building in African markets.',
      primaryFocus: 'Primary focus',
      primaryFocusValue: 'Secure product delivery',
      workingStyle: 'Working style',
      workingStyleValue: 'Hands-on assessment and build support',
      clientsKicker: 'Trusted ecosystem',
      clientsTitle: 'Built around ambitious African teams.',
      clientsBody: 'Partners, builders, and early customers help shape a security practice that is practical, local, and ready for scale.',
    },
    footer: {
      kicker: 'Security intelligence',
      title: 'Start with a focused assessment.',
      summary: 'Secure digital platforms, offensive security assessments, cloud hardening, and managed protection for modern African businesses.',
      services: 'Services',
      company: 'Company',
      newsletter: 'Newsletter',
      newsletterBody: 'Security notes, service updates, and practical guidance.',
      emailPlaceholder: 'Email address',
      subscribed: 'Thank you for subscribing.',
      rights: 'All rights reserved.',
    },
  },
  sw: {
    controls: {
      themeLight: 'Mwanga',
      themeDark: 'Giza',
      language: 'Lugha',
      english: 'EN',
      swahili: 'SW',
    },
    nav: {
      home: 'Mwanzo',
      services: 'Huduma',
      identity: 'Utambulisho',
      insights: 'Maarifa',
      developers: 'Wabunifu',
      contact: 'Wasiliana',
      more: 'Zaidi',
      careers: 'Kazi',
      shop: 'Duka',
      support: 'Msaada wa Xempi',
      solutions: 'Suluhisho',
      searchPlaceholder: 'Tafuta huduma za usalama',
      searchServices: 'Tafuta huduma',
      requestAssessment: 'Omba tathmini',
    },
    topbar: {
      hours: 'Jumatatu-Ijumaa: 9AM-5PM',
      login: 'Ingia',
      signup: 'Jisajili',
    },
    auth: {
      loginTitle: 'Ingia kwenye akaunti ya SeptaGreen',
      signupTitle: 'Fungua akaunti ya SeptaGreen',
      email: 'Barua pepe',
      workEmail: 'Barua pepe ya kazi',
      password: 'Nenosiri',
      confirmPassword: 'Thibitisha nenosiri',
      fullName: 'Jina kamili',
      remember: 'Nikumbuke',
      forgot: 'Umesahau nenosiri?',
      signIn: 'Ingia',
      signingIn: 'Inaingia...',
      signUp: 'Jisajili',
      processing: 'Inashughulikiwa...',
      loginSuccess: 'Umeingia kikamilifu.',
      signupSuccess: 'Akaunti imeundwa kikamilifu.',
      noAccount: 'Huna akaunti?',
      hasAccount: 'Una akaunti tayari? Ingia',
      emailPlaceholder: 'Weka barua pepe yako',
      passwordPlaceholder: 'Weka nenosiri lako',
      passwordRules: 'Nenosiri liwe na:',
      ruleLength: 'Angalau herufi 8',
      ruleUppercase: 'Herufi kubwa moja',
      ruleLowercase: 'Herufi ndogo moja',
      ruleNumber: 'Nambari moja',
      ruleSpecial: 'Alama maalum moja',
    },
    home: {
      badge: 'Usalama shambulizi, mifumo salama, na ulinzi endelevu',
      title: 'Maarifa ya usalama kwa wajenzi wa kidijitali Afrika.',
      body: 'SeptaGreen husaidia timu kujenga, kujaribu, na kufuatilia mifumo ya kidijitali kabla udhaifu haujaleta madhara ya biashara.',
      primary: 'Omba tathmini',
      secondary: 'Chunguza huduma',
    },
    mid: {
      kicker: 'Uhakika wa usalama',
      title: 'Usalama unaotegemea ushahidi kwa timu zinazohitaji kusonga haraka.',
      body: 'Kila kazi inalenga matokeo yanayosaidia maamuzi, ushahidi wa kiufundi, na hatua zinazofahamika kwa wahandisi na viongozi.',
      rhythmKicker: 'Mpangilio wa kazi',
      rhythmTitle: 'Kutoka tathmini hadi hatua.',
      consultant: 'Zungumza na mshauri wa usalama',
    },
    services: {
      kicker: 'Huduma za kitaalamu za upimaji usalama',
      title: 'Jaribu ulinzi wako kabla washambuliaji hawajafanya hivyo.',
      body: 'SeptaGreen huunganisha upimaji shambulizi, ujenzi salama wa bidhaa, ukaguzi wa wingu, na ufuatiliaji kwa timu zinazohitaji kupunguza hatari kwa uwazi.',
      discover: 'Gundua huduma zetu kwa',
      discoverTitle: 'Timu za kisasa, mifumo muhimu, na ukuaji wa kidijitali.',
      learnMore: 'Jifunze zaidi',
    },
    contact: {
      kicker: 'Omba tathmini',
      title: 'Linda biashara yako dhidi ya vitisho vya sasa vya mtandao.',
      body: 'Tuambie kuhusu mifumo, wingu, programu, au watumiaji unaohitaji kukagua. Tutapendekeza tathmini inayofaa na hatua inayofuata.',
      phoneTitle: 'Unapendelea mazungumzo ya moja kwa moja?',
      phoneBody: 'Piga simu kwa upangaji wa haraka au tuma fomu kwa ombi rasmi la tathmini.',
      emailLabel: 'Barua pepe',
      location: 'Mahali',
      nextTitle: 'Hatua inayofuata',
      nextSteps: [
        'Tunapitia mifumo, malengo, na muda wako.',
        'Tunapendekeza wigo sahihi wa tathmini.',
        'Unapokea hatua inayofuata na makadirio ya kazi.',
      ],
      formTitle: 'Pata wigo wa tathmini',
      formBody: 'Tuma muktadha wa kutosha ili tupendekeze njia sahihi ya usalama.',
      firstName: 'Jina la kwanza',
      lastName: 'Jina la mwisho',
      email: 'Barua pepe ya kampuni',
      phone: 'Simu',
      company: 'Jina la kampuni',
      service: 'Huduma inayohitajika',
      offensive: 'Huduma ya usalama shambulizi',
      penetration: 'Huduma ya penetration testing',
      cloud: 'Huduma ya usalama wa wingu',
      app: 'Huduma ya usalama wa programu',
      managed: 'Huduma ya usalama unaosimamiwa',
      solution: 'Suluhisho linalohitajika',
      timeline: 'Muda',
      timelineOptions: ['Mwezi huu', 'Miezi 1-3', 'Robo hii', 'Uchunguzi wa awali'],
      message: 'Muktadha wa mradi',
      messagePlaceholder: 'Mifumo, URLs, majukwaa ya wingu, mahitaji ya compliance, au wasiwasi uliopo',
      submit: 'Omba tathmini',
      success: 'Asante. Timu ya SeptaGreen itawasiliana nawe kwa hatua inayofuata.',
    },
    identity: {
      missionKicker: 'Utambulisho wa SeptaGreen',
      missionTitle: 'Usalama wa Afrika, ulioundwa kwa nidhamu.',
      missionBody: 'SeptaGreen ipo kwa mashirika yanayohitaji ukuaji salama wa kidijitali bila maigizo. Tunaunganisha uhandisi wa bidhaa, upimaji shambulizi, na uwazi wa uendeshaji ili timu zijue nini cha kurekebisha, kwa nini ni muhimu, na jinsi ya kuboresha.',
      missionCta: 'Omba tathmini',
      signals: [
        ['Jenga kwa usalama', 'Mifumo, API, na majukwaa hutazamwa kama sehemu za usalama tangu mwanzo.'],
        ['Pima kwa uhalisia', 'Tathmini hulenga njia halisi za shambulio, si ripoti zilizotiwa chumvi.'],
        ['Ripoti kwa uwazi', 'Matokeo huandikwa kwa watu wanaofadhili, kurekebisha, na kuthibitisha kazi.'],
      ],
      valuesKicker: 'Kanuni za kazi',
      valuesTitle: 'Kinachoongoza kazi yetu.',
      valuesBody: 'Nembo na uzoefu wa SeptaGreen unapaswa kuhisi makini, wa karibu, na tulivu chini ya shinikizo. Kanuni hizi huweka kazi na utambulisho pamoja.',
      values: [
        ['Uadilifu kuliko maigizo', 'Tunaweka matokeo kwa usahihi, ushahidi, na matumizi ya moja kwa moja. Hatukuzi hatari bila sababu.'],
        ['Utekelezaji uliopimwa', 'Kazi ya usalama lazima iheshimu muda wa huduma, muktadha wa biashara, uwezo wa wahandisi, na ukuaji wa timu.'],
        ['Ubunifu unaoelewa Afrika', 'Mazingira ni muhimu: malipo, watumiaji wa simu, miundombinu ya karibu, na mahitaji ya kikanda.'],
        ['Ushirikiano wa karibu', 'Tunafanya kazi na timu zinazorekebisha ili usalama uwe tabia ya kurudiwa, si ripoti ya mara moja.'],
      ],
      timelineKicker: 'Njia ya kampuni',
      timelineTitle: 'Mpango halisi, si ahadi tupu.',
      timelineBody: 'Tovuti inapaswa kuonyesha mwelekeo bila kujifanya kubwa kuliko ilivyo. Mstari huu unaweka hadithi kuwa ya kuaminika na ya sasa.',
      milestones: [
        ['2025', 'Msingi nchini Kenya', 'SeptaGreen inaanza kwa kuunganisha ujenzi salama wa programu, upimaji wa usalama, na ushauri wa vitendo kwa timu za Afrika.'],
        ['2026', 'Utoaji unaoanza na tathmini', 'Mfumo wa huduma unaimarishwa kwenye red team, usalama wa programu, ukaguzi wa wingu, na ufuatiliaji.'],
        ['Ijayo', 'Kuwawezesha developers', 'DeveloperX inapanua chapa kupitia viwango, orodha za ukaguzi, mapitio ya bidhaa, na uhandisi wenye usalama.'],
        ['Ukuaji', 'Kuboresha endelevu', 'SeptaGreen inakua kuelekea ufuatiliaji, retesting, ripoti, na ushirikiano wa muda mrefu wa usalama.'],
      ],
      leadershipKicker: 'Uongozi',
      leadershipTitle: 'Imejengwa na watendaji walio karibu na kazi.',
      leadershipBody: 'Hadithi ya uongozi iwe ya moja kwa moja: mtu nyuma ya kazi, falsafa ya uendeshaji, na njia za kuthibitisha uaminifu.',
      leaderRole: 'Mwanzilishi na Lead Builder',
      leaderBio: 'William huunganisha uundaji wa programu, mazoezi ya cybersecurity, na fikra za bidhaa. SeptaGreen inaonyesha muunganiko huo: bidhaa zinazotumika, usalama imara, na mwongozo wa vitendo kwa timu za Afrika.',
      primaryFocus: 'Lengo kuu',
      primaryFocusValue: 'Utoaji salama wa bidhaa',
      workingStyle: 'Mtindo wa kazi',
      workingStyleValue: 'Tathmini na msaada wa kujenga kwa vitendo',
      clientsKicker: 'Mtandao wa uaminifu',
      clientsTitle: 'Tumezungukwa na timu jasiri za Afrika.',
      clientsBody: 'Washirika, wajenzi, na wateja wa mwanzo husaidia kuunda huduma ya usalama inayotekelezeka, ya karibu, na tayari kukua.',
    },
    footer: {
      kicker: 'Maarifa ya usalama',
      title: 'Anza na tathmini yenye mwelekeo.',
      summary: 'Mifumo salama ya kidijitali, tathmini za usalama shambulizi, uimarishaji wa wingu, na ulinzi unaosimamiwa kwa biashara za kisasa Afrika.',
      services: 'Huduma',
      company: 'Kampuni',
      newsletter: 'Jarida',
      newsletterBody: 'Taarifa za usalama, masasisho ya huduma, na mwongozo wa vitendo.',
      emailPlaceholder: 'Barua pepe',
      subscribed: 'Asante kwa kujisajili.',
      rights: 'Haki zote zimehifadhiwa.',
    },
  },
};

export function SitePreferencesProvider({ children }) {
  const [theme, setTheme] = useState(() => localStorage.getItem('sg-theme') || 'light');
  const [language, setLanguage] = useState(() => localStorage.getItem('sg-language') || 'en');

  useEffect(() => {
    const root = document.documentElement;
    root.classList.toggle('dark', theme === 'dark');
    root.setAttribute('data-theme', theme);
    localStorage.setItem('sg-theme', theme);
  }, [theme]);

  useEffect(() => {
    document.documentElement.lang = language === 'sw' ? 'sw' : 'en';
    localStorage.setItem('sg-language', language);
  }, [language]);

  const value = useMemo(
    () => ({
      theme,
      language,
      text: copy[language] || copy.en,
      setTheme,
      setLanguage,
      toggleTheme: () => setTheme((current) => (current === 'dark' ? 'light' : 'dark')),
      toggleLanguage: () => setLanguage((current) => (current === 'sw' ? 'en' : 'sw')),
    }),
    [language, theme]
  );

  return <SitePreferencesContext.Provider value={value}>{children}</SitePreferencesContext.Provider>;
}

export function useSitePreferences() {
  const context = useContext(SitePreferencesContext);

  if (!context) {
    throw new Error('useSitePreferences must be used inside SitePreferencesProvider');
  }

  return context;
}
